name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    strategy:
      matrix:
        dotnet-version: ['5.0.x' ]
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
        run: dotnet restore
    - name: Build
        run: dotnet build --configuration Release --no-restore
    - name: Test
        run: dotnet test --no-restore --verbosity normal